//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class monster
    {
        public int MonsterID { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public string Type { get; set; }
        public string Align { get; set; }
        public string Challenge { get; set; }
        public string XP { get; set; }
        public Nullable<double> CR { get; set; }
        public Nullable<int> AC { get; set; }
        public Nullable<int> HP { get; set; }
        public string Hit_Dice { get; set; }
        public string Speeds { get; set; }
        public Nullable<int> STR { get; set; }
        public Nullable<int> DEX { get; set; }
        public Nullable<int> CON { get; set; }
        public Nullable<int> INT { get; set; }
        public Nullable<int> WIS { get; set; }
        public Nullable<int> CHA { get; set; }
        public string Sav_Throws { get; set; }
        public string Skills { get; set; }
        public string WRI { get; set; }
        public string Senses { get; set; }
        public string Languages { get; set; }
        public string Additional { get; set; }
        public string Actions { get; set; }
        public string Arctic { get; set; }
        public string Coast { get; set; }
        public string Desert { get; set; }
        public string Forest { get; set; }
        public string Grassland { get; set; }
        public string Hill { get; set; }
        public string Mountain { get; set; }
        public string Swamp { get; set; }
        public string Underdark { get; set; }
        public string Underwater { get; set; }
        public string Urban { get; set; }
        public string Font { get; set; }
        public string Add_Info { get; set; }
    }
}
